"""empty message

Revision ID: 7c7fd74024dc
Revises: f0d79cf2663a
Create Date: 2025-11-16 17:18:21.218293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7fd74024dc'
down_revision = 'f0d79cf2663a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('master_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'master', ['master_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('master_id')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
